# Generated by Django 3.1.7 on 2021-03-25 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraComandaModel',
            fields=[
                ('cabeceraId', models.AutoField(db_column='cabecera_id', primary_key=True, serialize=False, unique=True)),
                ('cabeceraFecha', models.DateField(db_column='cabecera_fecha')),
                ('cabeceraTotal', models.DecimalField(db_column='cabecera_total', decimal_places=2, max_digits=5)),
                ('cabeceraCliente', models.TextField(db_column='cabecera_cliente')),
            ],
            options={
                'verbose_name': 'comanda cabecera',
                'db_table': 't_comanda_cabecera',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteModel',
            fields=[
                ('comprobanteId', models.AutoField(db_column='comprobante_id', primary_key=True, serialize=False, unique=True)),
                ('comprobanteSerie', models.CharField(db_column='comprobante_serie', max_length=4)),
                ('comprobanteNumero', models.IntegerField(db_column='comprobante_numero')),
                ('comprobantePdf', models.URLField(db_column='comprobante_pdf')),
                ('comprobanteCdr', models.URLField(db_column='comprobante_cdr')),
                ('comprobanteXml', models.URLField(db_column='comprobante_xml')),
                ('comprobanteRuc', models.CharField(db_column='comprobante_ruc', max_length=11)),
            ],
            options={
                'verbose_name': 'comprobante',
                'db_table': 't_comprobante',
            },
        ),
        migrations.CreateModel(
            name='PersonalMesaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaId', models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.CASCADE, related_name='mesaPersonales', to='restaurante.mesamodel')),
                ('personalId', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, related_name='personalMesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personal mesa',
                'db_table': 't_personal_mesa',
            },
        ),
        migrations.CreateModel(
            name='DetalleComandaModel',
            fields=[
                ('detalleId', models.AutoField(db_column='detalle_id', primary_key=True, serialize=False, unique=True)),
                ('detalleCantidad', models.IntegerField(db_column='detalle_cantidad')),
                ('detalleSubtotal', models.DecimalField(db_column='detalle_subtotal', decimal_places=2, max_digits=5)),
                ('cabecera', models.ForeignKey(db_column='cabecera_id', on_delete=django.db.models.deletion.PROTECT, to='restaurante.cabeceracomandamodel')),
                ('plato', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, to='restaurante.platomodel')),
            ],
            options={
                'verbose_name': 'detalle comanda',
                'db_table': 't_comanda_detalle',
            },
        ),
        migrations.AddField(
            model_name='cabeceracomandamodel',
            name='comprobante',
            field=models.OneToOneField(db_column='comprobante_id', on_delete=django.db.models.deletion.CASCADE, to='restaurante.comprobantemodel'),
        ),
        migrations.AddField(
            model_name='cabeceracomandamodel',
            name='mesa',
            field=models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.PROTECT, to='restaurante.mesamodel'),
        ),
        migrations.AddField(
            model_name='cabeceracomandamodel',
            name='mozo',
            field=models.ForeignKey(db_column='mozo_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
