# Generated by Django 3.1.7 on 2021-03-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_auto_20210326_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecomandamodel',
            name='cabecera',
            field=models.ForeignKey(db_column='cabecera_id', on_delete=django.db.models.deletion.PROTECT, related_name='cabeceraDetalles', to='restaurante.cabeceracomandamodel'),
        ),
        migrations.AlterField(
            model_name='detallecomandamodel',
            name='plato',
            field=models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, related_name='platoDetalles', to='restaurante.platomodel'),
        ),
    ]
