# Generated by Django 3.1.7 on 2021-03-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0009_comprobantemodel_comprobantetipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteCdr',
            field=models.URLField(db_column='comprobante_cdr', null=True),
        ),
    ]
