# Generated by Django 3.1.7 on 2021-03-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteDni',
            field=models.CharField(db_column='cli_dni', max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
