# Generated by Django 3.1.7 on 2021-03-18 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20210317_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieModel',
            fields=[
                ('especieId', models.AutoField(db_column='especie_id', primary_key=True, serialize=False, unique=True)),
                ('especieNombre', models.CharField(db_column='especie_nombre', max_length=45)),
            ],
            options={
                'verbose_name': 'Especie',
                'db_table': 't_especie',
            },
        ),
        migrations.AlterModelOptions(
            name='razamodel',
            options={'verbose_name': 'raza'},
        ),
        migrations.RemoveField(
            model_name='mascotamodel',
            name='tipo',
        ),
        migrations.AddField(
            model_name='mascotamodel',
            name='raza',
            field=models.ForeignKey(db_column='raza_id', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='mascotasRaza', to='administracion.razamodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TipoModel',
        ),
        migrations.AddField(
            model_name='razamodel',
            name='especie',
            field=models.ForeignKey(db_column='especie_id', default=None, help_text='Id de la especie', on_delete=django.db.models.deletion.PROTECT, related_name='especiesRaza', to='administracion.especiemodel', verbose_name='Especie'),
            preserve_default=False,
        ),
    ]
