# Generated by Django 3.1.7 on 2021-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20210317_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiemodel',
            name='especieNombre',
            field=models.CharField(db_column='especie_nombre', max_length=45, unique=True),
        ),
    ]
