# Generated by Django 3.1.7 on 2021-03-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20210318_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especiemodel',
            options={'verbose_name': 'especie'},
        ),
        migrations.AddField(
            model_name='especiemodel',
            name='especieEstado',
            field=models.BooleanField(db_column='especie_estado', default=True),
        ),
        migrations.AlterField(
            model_name='especiemodel',
            name='especieNombre',
            field=models.CharField(db_column='especie_nombre', max_length=45, unique=True, verbose_name='nombre'),
        ),
    ]
